logging:
  file:
    enable: true
    level: INFO
    path: logs
    rotation: "10 MB"
    retention: "7 days"
  console:
    enable: true
    level: INFO

db_meta:
  host: localhost
  port: 3306
  user: root
  password: 1234
  database: meta

db_dw:
  host: localhost
  port: 3306
  user: root
  password: 1234
  database: dw

qdrant:
  host: localhost
  port: 6333
  embedding_size: 1024

embedding:
  host: localhost
  port: 8081
  model: BAAI/bge-large-zh-v1.5


es:
  host: localhost
  port: 9200
  index_name: data_agent


llm:
  model_name: deepseek-chat
  api_key: sk-87d6425e08a444b09c4dcd032d1c5467

langfuse:
  enabled: true
  secret_key: "sk-lf-dcb17211-933f-425e-b87a-0f63730b736a"
  public_key: "pk-lf-c5fd8778-8e83-4765-8397-8e98facfc006"
  host: https://cloud.langfuse.com
